### ISSUE TITLE
pull working version

### ISSUE THREAD

**Issue by vientodelbosque** [rpnow/rpnow#3]
The last pull of master branch its not working; it throws an error on room.php line 77 after creating a room (colum not found: room_number). After executing the update.sql (line by line; there are columns already created) can create a room but messages and characters are not saved

**Comment by shamblesides** [comment]
I'll look into it! Would you mind giving me your PHP version and MySQL version for reference?

**Comment by vientodelbosque** [comment]
Thank you! 
About the versions:
php 5.6.10
MySql 5.5.44

Also tried on a local server with the last distribution of xampp (php 5.6.14)

**Comment by vientodelbosque** [comment]
Ahora response :)

I've solved the problems doing the following:

-run the update.sql LINE BY LINE (a few lines fail to execute, so is it needed to executing 1 by 1)
-on Room.php, line 152, add this line $n2=intval($n);
-on Room.php, line 153, change intval($n) by $n2 ($statement->bindParam fails if you pass a function instead of a pure variable)

I think this is all :D :dancer:

**Comment by shamblesides** [comment]
fixed with sasza-works' changes.
