### ISSUE TITLE
Setup on existing Webserver

### ISSUE THREAD

**Issue by DeastinY** [rpnow/rpnow#70]
Hey there, great work !

So I tried setting up rpnow2 on an already existing webserver. 
Therefor I changed the production config to use port `8123:80` and setup the following in my regular nginx : 

```
server {
  listen 80;
  listen [::]:80;
  server_name myurl;

  location / {
    proxy_pass http://127.0.0.1:8123;
  }
}
```

Now I get a '500 Internal Server Error'  :disappointed: 

The nginx log states `"/dev/null/index.html" is not found (20: Not a directory), client: 127.0.0.1, server: _, request: "GET / HTTP/1.0"`

`docker -s` shows :
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS                           NAMES
e4ab5eb5bb8d        nginx:1.10          "nginx -g 'daemon ..."   28 hours ago        Up About a minute               443/tcp, 0.0.0.0:8123->80/tcp   e4ab5eb5bb8d_rpnow2_web_1```

I'm completely new to Docker, so it probably is not an Issue with your project, but my inexperience.
Would be nice if you could help though :wink:

**Comment by DeastinY** [comment]
Yeah, guess it would help :) Anyways thanks for the response, good luck with the moving and enjoy your wedding ! Cheers to you :clinking_glasses:  !

**Comment by shamblesides** [comment]
Hey, I've made lots of improvements to the docker setup lately. There's a lot less undocumented steps to making it work now. If you're still interested, give this another try and see if it works!

**Comment by DeastinY** [comment]
I'll look into it 😄 
Thanks for the update, glad you're doing well!

**Comment by shamblesides** [comment]
Open up a new issue if you still have any questions!
