### ISSUE TITLE
Can't run on Debian Linux

### ISSUE THREAD

**Issue by wolfy01** [rpnow/rpnow#75]
I know how to run it using to normal installation guide, But i've wanted to make some changes to some things, But I can't since trying to use the one from this GitHub so I can edit files doesn't work. Since the app ends up crashing for some odd reason, i've tried to fix to issue but anything I try doesn't work.

**Comment by bibichuuu** [comment]
Hello.Im not the creator of this project but you can send a mail et rpnow.net@gmail.com.Thanks 

Envoyé depuis Yahoo Mail pour Android 
 
  Le mar., juin 25, 2019 à 4:14, wolfy01<notifications@github.com> a écrit :   
I know how to run it using to normal installation guide, But i've wanted to make some changes to some things, But I can't since trying to use the one from this GitHub so I can edit files doesn't work. Since the app ends up crashing for some odd reason, i've tried to fix to issue but anything I try doesn't work.

**Comment by shamblesides** [comment]
Hey there, can you show the error message you're receiving?

**Comment by wolfy01** [comment]
----
[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `RPNOW_DATA_DIR=../data RPNOW_PORT=13000 go run -tags dev . -- server || exit 1`
2019/06/25 14:16:47 **dev mode**
2019/06/25 14:16:47 Loaded config at /etc/rpnow.ini
2019/06/25 14:16:47 Loaded some environment values
2019/06/25 14:16:47 Failed to open database: open ../data/rpnow.boltdb: no such file or directory
exit status 1
[nodemon] app crashed - waiting for file changes before starting...
----
@shamblesides

**Comment by shamblesides** [comment]
You may not have the latest version; try doing `git pull`

**Comment by wolfy01** [comment]
Well I just installed the latest version, and i'm still getting the same error

**Comment by wolfy01** [comment]
I fixed the issue, the path for index.html was wrong

**Comment by shamblesides** [comment]
The path to index.html is correct, and cloning a fresh version of this repo works fine for me. Did you run `npm install` and `npm run build` inside the `client/` folder before you tried to run the server?

**Comment by wolfy01** [comment]
yes

**Comment by wolfy01** [comment]
It seems to work fine for me now. Btw how do you change the site security and stuff?

**Comment by shamblesides** [comment]
Where did you change the location of index.html?

**Comment by shamblesides** [comment]
If you have built a binary version of RPNow, just run that. It should connect to the currently running server.

**Comment by wolfy01** [comment]
i put it in my worksapce folder.

**Comment by wolfy01** [comment]
And I still don't know how to change the site security and stuff.
