### ISSUE TITLE
Is it possible to run rpnow on windows?

### ISSUE THREAD

**Issue by wolfy01** [rpnow/rpnow#77]

**Comment by shamblesides** [comment]
Possibly, though I haven't tested it so it might need a couple tweaks.

**Comment by wolfy01** [comment]
Yes, it is possible, the only thing that doesn't work is the admin console, but other than that, it works just fine

**Comment by wolfy01** [comment]
Turns out using Ubuntu Linux from the Microsoft Store works just fine, In fact, I think this is the best way to host it from windows if you ever have to.
